name: alita_ecommerce
description: A modern Flutter e-commerce app with Clean Architecture and BLoC.

# No need to update this for now
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.5
  intl: ^0.19.0
  flutter_dotenv: ^5.0.2
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  formz: ^0.6.0
  
  # DI
  get_it: ^7.6.0
  injectable: ^2.1.2
  
  # Navigation
  auto_route: ^7.4.0
  
  # Network
  dio: ^5.1.2
  connectivity_plus: ^4.0.1
  
  # Storage
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.0
  
  # UI
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.6
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.6.2
  badges: ^3.1.1
  
  # Utils
  logger: ^1.3.0
  url_launcher: ^6.1.11
  share_plus: ^7.0.2
  image_picker: ^0.8.7+5
  geolocator: ^9.0.2
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  smooth_page_indicator: ^1.2.1
  
  # Firebase (Uncomment when needed)
  # firebase_core: ^2.13.1
  # firebase_auth: ^4.6.2
  # firebase_analytics: ^10.4.2
  # firebase_crashlytics: ^3.3.2
  # firebase_messaging: ^14.6.2
  # cloud_firestore: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  auto_route_generator: ^7.1.1
  injectable_generator: ^2.1.6
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0
  mockito: ^5.4.0
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true
  
  assets:
    - app.env
    - app.dev.env
    - app.staging.env
    - app.prod.env
    - assets/images/
    - assets/icons/
    - assets/fonts/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900