name: alita_ecommerce
description: "Alita Ecommerce"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  infinite_scroll_pagination: ^4.0.0
  
  # BLoC Pattern
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  formz: ^0.7.0
  form_bloc: ^0.31.0
  
  # Networking & API
  dio: ^5.4.1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  connectivity_plus: ^5.0.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # Navigation
  auto_route: ^7.9.0
  
  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.3
  
  # Authentication
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  
  # Payment
  flutter_stripe: ^10.1.0
  
  # Utilities
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  flutter_dotenv: ^5.1.0
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  permission_handler: ^11.2.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  
  # Performance & Analytics
  firebase_analytics: ^10.8.5
  firebase_crashlytics: ^3.4.9
  
  # Code Generation Related
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  
  # Testing
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  
  # App Icons & Splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
  
# Splash Screen Configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash/splash.png"
  android_12:
    image: "assets/splash/splash.png"
    color: "#FFFFFF"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    # - .env

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800